# -*- coding: utf-8 -*-
"""Taller_2_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B13Q6O8WgrzrYoo6RBINIdZyW42bL0Mg
"""

existe = [] # Lista para agregar las que existen
no_existe = [] # Lista para agregar las que no  existen
def contar_vocales(palabra):
  for i in palabra:
    contador = 0
    for letra in palabra:
      if letra.lower() in "aeiou": # Busca si la pañanra tiene una de las 5 vocales en mayuscula o miniscula
        contador += 1 # Cuente el contador
    if contador >= 2: # Si el contador es mayor o igual a 2 retorne la palabra y la agregue a la lista que existe
      existe.append(palabra)
      return palabra
    else:
      no_existe.append(palabra) # Si el contador es menor a 2 retorne no existe y la agregue a la lista que no existe
      return "No existe"

if __name__ == "__main__":
  palabras_ = []
  num = int(input("Ingresa el número de palabras que desees ")) # Determine cuantas palabras quiere
  for i in range(num):
    palabra_ = input("Ingrese la palabra que desee ") # Ingrese la palabra
    palabras = palabra_  # Variable auxiliar
    palabras_.append(palabras) # Agregar palabras con la lista auxilair a a lista
    existe_o_no = contar_vocales(palabra_) #Ejecutar la función
    print(existe_o_no)
  print("Todas las palanras que pusiste son " +str(palabras_))
  print("Las que existen " +str(existe))
  print("Las que no existen " +str(no_existe))