# -*- coding: utf-8 -*-
"""Taller_2_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wf9pnozashV1cFJp2ikytDmF4-7QzuRH
"""

a = int(input("Ingresa un numero: "))
b = int(input("Ingresa ahora otro número: "))
def MCD(a, b):
    if b == 0:
        return a
    else:
        return MCD(b, a % b)

def MCM(a, b):
    return a * b // MCD(a, b)


print(f"El mínimo común multiplo de {a} y {b} es: {MCM(a, b)}")